Isabellewei/account number
celo-org/wallet pull request #434
Opened 2021-06-01 18:27 UTC by isabellewei

### Description

Update Account Number design, add a visual "Tap to Copy" indicator

### Tested

![Screenshot_1622570174](https://user-images.githubusercontent.com/15326838/120372694-7ddf0800-c2e5-11eb-99ca-ac54080e4cad.png)
![Screenshot_1622570318](https://user-images.githubusercontent.com/15326838/120372696-7e779e80-c2e5-11eb-9e0e-20f630030625.png)
![Screenshot_1622570188](https://user-images.githubusercontent.com/15326838/120372699-7f103500-c2e5-11eb-8ebc-515c3f16d891.png)

### Related issues

- Fixes #303

2021-06-01 21:16 UTC, gnardini reviewed
Looks great!! 🚀

2021-06-01 21:16 UTC, gnardini commented on packages/mobile/src/components/AccountNumber.tsx
> +  const addressString = '0x ' + addressChunks.reduce((x, y) => x + ' ' + y)
This didn't have any tests but it'd probably be good to add some :D Maybe just checking that the address is populated correctly with the right spaces and that on press the `Clipboard.setString` function gets called with the right parameter?

2021-06-03 10:16 UTC, jeanregisser requested changes
Nice 👍 

Is the "payment sent" screenshot in the PR outdated? According to the Figma design, the address shouldn't be limited to 5 chunks in the first line.
<img width="405" alt="Screenshot 2021-06-03 at 12 12 34" src="https://user-images.githubusercontent.com/57791/120628588-25cf0f80-c465-11eb-9ac6-dd5eec76a5b5.png">

2021-06-03 10:16 UTC, jeanregisser commented on packages/mobile/src/transactions/UserSection.tsx
> +            <Text style={styles.accountLabel}>{t('dappkit:address')}</Text>
We should keep `accountNumberLabel` and update the locale instead.

2021-06-06 02:18 UTC, isabellewei commented
@jeanregisser thanks, I've fixed it 🙏

2021-06-08 10:26 UTC, jeanregisser approved these changes
Nice, ship it 👍

2021-06-09 01:43 UTC, merged

2021-06-10 19:52 UTC, MuckT commented
@isabellewei looks like these changes impacted the cash in / cash out cryptocurrency exchange account number.

![Simulator Screen Shot - iPhone 8 - 2021-06-10 at 12 43 08](https://user-images.githubusercontent.com/26950305/121587552-cc795a00-c9e9-11eb-858b-879714c09d3a.png)

Applying the below styles `AccountNumber.tsx` appears to fix the issue on iOS and Android.
```JavaScript
return touchDisabled ? (
    <Text style={styles.text}>{addressString}</Text>
  ) : (
    <TouchableOpacity
      onLongPress={onPressAddress}
      onPress={onPressAddress}
      testID="CopyAddressToClipboard"
      style={{flexShrink:1}}
    >
      <Text style={styles.text}>{addressString}</Text>
    </TouchableOpacity>
  )
```

2021-07-09 12:20 UTC, Celoqa commented
Hi @MuckT Again We have cross verified this issue on Latest android build V1.16.1 & Testflight build V1.16.1(67) and updated the status in testqulaity tool.

**Testquality tool link:**

**Android:**

- https://valora.testquality.com/project/12128/plan/20854/run/148956/result/2432161
**iOS:**

- https://valora.testquality.com/project/12128/plan/20854/run/148956/result/2432189

And also we have tested #482 


**Devices:** Vivo v11 pro (10), iPhone 6+(12.4.5)

CC: @isabellewei