Allow opening in-app notifications in external browser
celo-org/wallet pull request #473
Opened 2021-06-10 11:15 UTC by Pedro-vk

### Description

_Allow opening in-app notifications in external browser_

### Tested

_Tested on Android_

### How others should test

_Creating or editing a notification in Firebase_

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/7929

### Backwards compatibility

_It is backward compatible, if the notification doesn't specify the external parameter, it takes "false" as default, that behaves like previous versions_

2021-06-10 21:52 UTC, etuleu approved these changes

2021-06-11 16:09 UTC, jeanregisser requested changes

2021-06-11 16:09 UTC, jeanregisser commented on packages/mobile/src/home/reducers.ts
> +  external?: boolean
Let's rename to keep it consistent with the naming used for push notification: https://github.com/celo-org/wallet/blob/c2cf2292a01d11fe53f23dae91f9a463b46da747/packages/mobile/src/firebase/notifications.ts#L96
```suggestion
  openExternal?: boolean
```

2021-06-29 12:18 UTC, jeanregisser reviewed
Thanks, could you also update `NotificationBox.test.tsxt` to cover this new use case?

2021-06-30 12:36 UTC, Pedro-vk commented
> Thanks, could you also update `NotificationBox.test.tsxt` to cover this new use case?

Done!

2021-06-30 12:59 UTC, jeanregisser approved these changes
Shiiip it 👍 🐑 :shipit:

2021-07-05 11:18 UTC, merged

2021-07-09 11:28 UTC, Celoqa commented
Hey @MuckT  I have verified this issue using  Android internal build V1.16.1 & Test Flight build V1.16.1(67) & updated our observation in below sheet.
**Sheet Link:** https://docs.google.com/spreadsheets/d/1wYi5kbe_NUXuhc9xtcbT9dtyrVbPXqNBrAETfSx0R58/edit#gid=1119817571&range=O2

**New bug:**

- https://github.com/celo-org/wallet/issues/859

**Verified On Devices:** Redmi Note 8 (9.0),Redmi Note 8 (10.0), Vivo V11 pro (10)
CC: @Pedro-vk